name: DOCS

on:
  push:
    branches: ["main"]
    paths:
      - '**.md'
      - 'documents/**'
      - 'media/**'
      - 'design/**'
      - 'info.yaml'
      - 'config.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  docs:
    uses: EneaDim/Tutorial1_SKY130/.github/workflows/docs.yaml@main
    permissions:
      contents: read
      pages: write
      id-token: write
